app:
    resource: "@AppBundle/Controller/"
    type:     annotation

mm_cmf_admin:
    resource: "@MMCmfAdminBundle/Resources/config/routing.yml"

mm_cmf_content:
    resource: "@MMCmfContentBundle/Resources/config/routing.yml"
    prefix:   /mmcmfcontent

#... other HERE routings ...

# put this at the very last
mm_cmf_routing:
    resource: "@MMCmfRoutingBundle/Resources/config/routing.yml"