imports:
  - { resource: "@MMAdminBundle/Resources/config/config.yml" }
  - { resource: "@MMCmfAdminRoutingAddonBundle/Resources/config/config.yml" }

mm_admin:
    appearance:
        name: CCDS4

    menu:
        main:
            groups:
                general:
                    label: ~
                    entries:
                        - {name: Dashboard, icon: dashboard, route: mm_admin_homepage}

#                entities:
#                    label: Daten
#                    icon: database
#                    entries:
#                        - {name: Cinemas, icon: home, route: admin_cinema_index}
#                        - {name: Movies, icon: film, route: admin_movie_index}
#                        - {name: Events, icon: calendar, route: admin_event_index}
#                        - {name: Scheduled Shows, icon: history, route: admin_showtime_schedule_index}

                cms:
                    label: Content Management
                    icon: ~
                    entries:
                        - {name: Pages, icon: file-o, route: mm_cmf_admin_page_addon_page}

                routing:
                    label: Routing
                    icon: ~
                    entries:
                        - {name: Route, icon: file-o, route: mm_cmf_admin_routing_addon_noderoute}

                user:
                    label: System Settings
                    icon: cogs
                    entries:
                        - {name: User, icon: users, route: mm_admin_user}