admin_index:
    resource: "@MMAdminBundle/Resources/config/routing.yml"
    prefix: /

mm_cmf_page_addon:
    resource: "@MMCmfAdminPageAddonBundle/Resources/config/routing.yml"
    prefix:   /page

mm_cmf_routing_addon:
    resource: "@MMCmfAdminRoutingAddonBundle/Resources/config/routing.yml"
    prefix:   /routing
